name: Trigger Automation for Docker update

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: "Version of the package to build"
        required: true
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  build-new-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^([0-9]+\.[0-9]+\.[0-9]+|unstable)$ ]]; then
            echo "Invalid version format. Expected format: x.y.z or 'unstable'"
            exit 1
          fi
      
      - name: Set up bashbrew
        uses: docker-library/bashbrew@v0.1.12
      
      - name: Check if bashbrew in installed
        run: |
          bashbrew --version

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Autxmaton/valkey-container
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Update new version
        run: |
          if [ -d "${{ inputs.version }}" ]; then
            echo "${{ inputs.version }} already exists."
            exit 1
          else
            mkdir ${{ inputs.version }}
            ./update.sh
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: update-${{ inputs.version }}
          commit-message: "Update to version ${{ inputs.version }}"
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Update to version ${{ inputs.version }}"
          body: |
            This pull request updates the repository to version `${{ inputs.version }}`.
            Please review the changes and merge when appropriate.
          