name: Trigger Automation for Docker update

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: "Version of the package to build"
        required: true
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  build-new-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^([0-9]+\.[0-9]+\.[0-9]+|unstable)$ ]]; then
            echo "Invalid version format. Expected format: x.y.z or 'unstable'"
            exit 1
          fi
      
      - name: Set up bashbrew
        uses: docker-library/bashbrew@v0.1.12
      
      - name: Check if bashbrew in installed
        run: |
          bashbrew --version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Autxmaton/valkey-container
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
      - name: Create new branch and update version
        run: |
          if [ -d "${{ github.event.inputs.version }}" ]; then
            echo "${{ github.event.inputs.version }} already exists."
            exit 1
          else
            NEW_BRANCH="update-${{ github.event.inputs.version }}"
            git checkout -b $NEW_BRANCH
            mkdir ${{ github.event.inputs.version }}
            ./update.sh
            git add .
            git commit -s -m "Update to ${{ github.event.inputs.version }}"
            git push origin $NEW_BRANCH
          fi

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.PAT_TOKEN }}
      #     branch: update-${{ github.event.inputs.version }}
      #     base: mainline
      #     title: "Update to version ${{ github.event.inputs.version }}"
      #     body: |
      #       This pull request updates the repository to version `${{ github.event.inputs.version }}`.
      #       Please review the changes and merge when appropriate.